# Generated by Django 4.2.7 on 2024-03-17 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='imade',
            new_name='image',
        ),
    ]
