# Generated by Django 4.2.7 on 2024-04-10 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_delivery_adress_order_delivery_address'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
    ]
